version: '3'
services:
  redis-master:
    image: redis:3-alpine
    ports:
      - 6379:6379
  redis-slave:
    image: redis:3-alpine
    command: redis-server --slaveof redis-master 6379
    links:
      - redis-master
    ports:
      - 6379
  redis-sentinel:
    build: redis
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000  
    ports:
      - 26379  
    links:
      - redis-master
      - redis-slave
  game-controller:
    build: game-controller
    ports:
      - 8080:8080  
    links:
      - redis-sentinel